#!/usr/bin/env bash
#script that displays Best School 10 times.

count=0

until [ $count -ge 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "hi"
		echo "Best School"
	else
		echo "Best School"
	fi
	((count++))
done
