#!/usr/bin/env bash
#script that displays Best School 10 times.

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 8 ]
	then
		echo "Best School"
		echo "hi"
	else
		echo "Best School"
	fi
	((count++))
done
