#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes:

hour=1

while [ $hour -lt 13 ]
do
	min=1

	echo "Hour: $hour"
	while [ $min -lt 60 ]
	do
		echo "$min"
		((min++))
	done
	((hour++))
done
