#!/usr/bin/env bash
#Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

temp="${PWD}/*"

for i in $temp ; do
    basename "$i" | cut -d "-" -f2
done
