#!/usr/bin/env bash
#Bash script that gives you information about the school file

temp="${PWD}/school"

if [ -e "$temp" ]
then
	echo "school file exists"
	if [ -s "$temp" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi
if [ -f "$temp" ]
then
	echo "school is a regular file"
fi
