#!/usr/bin/env bash
# Configuration of a UBUNTU server for localhost and facebook.com

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
sed -i '2i/8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
